name: easy_everything
description: A new Flutter package.
version: 0.0.6
homepage: https://github.com/lovekid1997/easy-everything

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0  
  rxdart: ^0.27.1
  auto_size_text: 3.0.0-nullsafety.0
  flutter_svg: ^0.22.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

