name: rounded_loading_button_gradient
description: A new Flutter package. Helping developers to build UI quickly, I try to build on existing widgets and make them useful and beautiful.
version: 0.1.1
homepage: https://github.com/lovekid1997/easy-everything

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  auto_size_text_pk: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  rxdart: ^0.27.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
